# name of the object to place
string object_id
# name of the arm, which holds the object
string arm
# the current planning scene
#arm_navigation_msgs/PlanningScene planning_scene
moveit_msgs/PlanningScene planning_scene
---
#arm_navigation_msgs/ArmNavigationErrorCodes error_code
moveit_msgs/MoveItErrorCodes error_code
