(define (problem p01)
  (:domain tidyup_grounding)
  (:moduleoptions
	(drive_pose_init@libplanner_modules_pr2.so) 
	(navigation_init@libplanner_modules_pr2.so)
	(robot_near_table_init@libplanner_modules_pr2.so)
	(pickup_init@libplanner_modules_pr2.so) 
	(putdown_init@libplanner_modules_pr2.so) 
  )
  (:moduleexitoptions (drive_pose_exit@libplanner_modules_pr2.so) )
  (:objects
    /map - frameid
    table1 table2 - table
    coke_1 - movable_object
  )
  (:init
    (= (robot-theta) -1.57588)
    (= (robot-x) 4.82629)
    (= (robot-y) 6.79231)
    (= (robot-torso-position) 0.2)
    (= (qw coke_1) 0.206869)
    (= (qx coke_1) 3.89773e-05)
    (= (qy coke_1) 0.000249538)
    (= (qz coke_1) 0.978369)
    (= (timestamp coke_1) 0)
    (= (x coke_1) 4.68993)
    (= (y coke_1) 5.43774)
    (= (z coke_1) 0.904716)
	(object-on coke_1 table1) 
    (= (qw table1) 1)
    (= (qx table1) 0)
    (= (qy table1) 0)
    (= (qz table1) 0)
    (= (timestamp table1) 0)
    (= (x table1) 4.81)
    (= (y table1) 5.28)
    (= (z table1) 0.9)
    (= (qw table2) 1)
    (= (qx table2) 0)
    (= (qy table2) 0)
    (= (qz table2) 0)
    (= (timestamp table2) 0)
    (= (x table2) 0.5)
    (= (y table2) 6.44)
    (= (z table2) 0.73)
    (= (arm-state left_arm) arm_unknown)
    (= (arm-state right_arm) arm_unknown)
    (= (frame-id table1) /map)
    (= (frame-id table2) /map)
  )
  (:goal (and
    ;(forall (?o - arm) (hand-free ?o))
    (forall (?o - table) (table-inspected ?o))
    ;(forall (?o - movable_object) (object-inspected ?o))
    (object-grasped coke_1 right_arm)
    ;(robot-near-table table1)
    ;(table-inspected table1)
  ))
)
