(define (problem p01)
  (:domain tidyup_grounding)
  (:moduleoptions
	(navstack_init@libplanner_modules_pr2.so /map 0.05 1)
	(lift_torso_init@libplanner_modules_pr2.so)
	(drive_pose_init@libplanner_modules_pr2.so) )
  (:moduleexitoptions (drive_pose_exit@libplanner_modules_pr2.so) )
  (:objects
    /map - frameid
    table1 table2 - table
  )
  (:init
    (= (current-torso-height) 0.802173)
    (= (sampled-torso-height) 0.802)
    (= (robot-theta) -1.57588)
    (= (robot-x) 4.82629)
    (= (robot-y) 6.79231)
    (= (qw table1) 1)
    (= (qx table1) 0)
    (= (qy table1) 0)
    (= (qz table1) 0)
    (= (timestamp table1) 0)
    (= (x table1) 4.81)
    (= (y table1) 5.28)
    (= (z table1) 0.9)
    (= (qw table2) 1)
    (= (qx table2) 0)
    (= (qy table2) 0)
    (= (qz table2) 0)
    (= (timestamp table2) 0)
    (= (x table2) 0.5)
    (= (y table2) 6.44)
    (= (z table2) 0.73)
    (= (arm-state left_arm) arm_unknown)
    (= (arm-state right_arm) arm_unknown)
    (= (frame-id table1) /map)
    (= (frame-id table2) /map)
  )
  (:goal (and
    (forall (?o - arm) (hand-free ?o))
    (forall (?o - table) (table-inspected ?o))
  ))
)
