header: 
  seq: 0
  stamp: 0
  frame_id: /head_mount_kinect_rgb_link
pose: 
  position: 
    x: 0.48
    y: -0.2
    z: 0
  orientation: 
    x: 0.255923
    y: 0.414539
    z: -0.743098
    w: -0.458766
