#!/bin/bash

. /opt/ros/fuerte/share/rosbash/rosbash

roscreate-pkg $1 tidyup_executive
mkdir -p $1/config/planning
mkdir -p $1/config/mapping
mkdir -p $1/maps
mkdir -p $1/launch
roscp tidyup_tools screen_m1.launch $1/launch/ 
roscp tidyup_tools screen_base.launch $1/launch/ 
roscp tidyup_tools tidyup.vcg $1/config
roscp tidyup_tools domain_tidyup.yaml $1/config/planning
roscp tidyup_tools planner_params_tidyup.yaml $1/config/planning
sed -i "s/CONFIG_PACKAGE/${1}/" "${1}/launch/screen_m1.launch"
