base_link: 'base_link'

# =====================================================
left_gripper:
    end_effector_name: 'left_gripper'  #ee group name

    #actuated joints in end effector, pr2 only has one moving joint in gripper
    joints : ['l_gripper_l_finger_joint']

    #open position
    #how wide should the gripper be opened (max = 0.55 in joint tics)
    pregrasp_posture : [0.55]
    pregrasp_time_from_start : 4.0

    #close position
    #how wide should the gripper be closed (min = 0 in joint tics)
    grasp_posture : [0.20]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [0, 0, 0]

    #desired pose from end effector to grasp - [r, p, y]
    # NOTE: only PITCH is implemented (y)!
    grasp_pose_to_eef_rotation : [0, 0, 0] # 1.5707 = PI/2

    end_effector_parent_link: 'l_wrist_roll_link'
# =====================================================
right_gripper:
    end_effector_name: 'right_gripper'  #ee group name

    #actuated joints in end effector
    joints : ['r_gripper_l_finger_joint']

    #open position
    # pregrasp_posture : [0.0095]
    pregrasp_posture : [0.35]
    pregrasp_time_from_start : 4.0

    #close position
    #grasp_posture : [-0.0125]
    grasp_posture : [0.00]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [-0.15, 0, 0]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 1.5708, 0] # 1.5707 = PI/2

    end_effector_parent_link: 'r_wrist_roll_link'

