state_creators:
    - tidyup_state_creators/state_creator_robot_pose robot-x robot-y robot-theta robot-torso-position robot-near-table
#    - tidyup_state_creators/state_creator_robot_pose robot_location location robot-at location
    - tidyup_state_creators/state_creator_arms_status right_arm_to_side left_arm_to_side right_arm_to_front left_arm_to_front arm-state arm_at_side arm_at_front arm_unknown
    - tidyup_state_creators/state_creator_from_planning_scene
#    - tidyup_state_creators/state_creator_lift_torso torso-position torso-lifted
#    - tidyup_state_creators/state_creator_lift_torso_grounding current-torso-height sampled-torso-height torso-lifted
goal_creators:
#    - tidyup_state_creators/goal_creator_tidyup_initialize
    - tidyup_state_creators/goal_creator_tidyup_initialize_grounding
    - tidyup_state_creators/goal_creator_load_tables_into_planning_scene table
    - tidyup_state_creators/goal_creator_define_goal
#    - tidyup_state_creators/goal_creator_from_planning_scene
action_executors:
    - object_manipulation_actions/action_executor_arm_to_side arm-to-side right_arm_to_side left_arm_to_side
    - object_manipulation_actions/action_executor_arm_to_front arm-to-front right_arm_to_front left_arm_to_front
#    - object_manipulation_actions/action_executor_inspect_location inspect-location /ork_to_planning_scene /head_traj_controller/point_head_action head_mount_kinect_rgb_link location-inspected location-inspected-recently
    - object_manipulation_actions/action_executor_inspect_table inspect-table /ork_to_planning_scene /head_traj_controller/point_head_action head_mount_kinect_rgb_link table-inspected table-inspected-recently
#    - object_manipulation_actions/action_executor_lift_torso lift-torso
    - object_manipulation_actions/action_executor_inspect_object inspect-object object-inspected
#    - object_manipulation_actions/action_executor_pickup_object pickup-object
    - object_manipulation_actions/action_executor_pickup_object_grounding pickup-object table-inspected-recently
#    - object_manipulation_actions/action_executor_putdown_object putdown-object
    - object_manipulation_actions/action_executor_putdown_object_grounding putdown-object table-inspected-recently
    - navigation_actions/action_executor_ros_navigation_grounding move-robot-to-table move_base table-inspected-recently sampled-torso-height
#    - navigation_actions/action_executor_ros_navigation move-robot move_base start location-inspected-recently false
#    - object_manipulation_actions/action_executor_detect_objects detect-objects /tidyup/detect_narf_objects /tidyup/request_graspability table2
#    - object_manipulation_actions/action_executor_arm_to_inspect_object arm-to-inspect-object /tidyup/inspect_action arm-state arm_unknown
